services:
  server:
    build:
      context: .
      target: final
    ports:
      - 4000:8080
    volumes:
      - ./Keys/serviceAccountKey.json:/app/Keys/serviceAccountKey.json
    environment:
      - CLIENT_DOMAIN=http://localhost:4000
      - GOOGLE_APPLICATION_CREDENTIALS=/app/Keys/serviceAccountKey.json
      - OPENAI_API_KEY=${OPENAI_API_KEY}
